version: '3.8'

services:
  web:
    build: .
    container_name: agenda_medica_app
    ports:
      - "5000:5000"
    # O comando abaixo instrui o Docker a carregar o nosso arquivo .env
    env_file:
      - .env
    # Mapeia a pasta local para dentro do container para não perdermos o SQLite
    volumes:
      - .:/app